### ISSUE TITLE
Show drive letters on Windows

### ISSUE THREAD

**Issue by martinlindhe** [MoAlyousef/sysinfo-gui#10]
Here's my Windows disks:

![image](https://user-images.githubusercontent.com/181531/168781865-29267bbf-4f8f-4d5e-97fd-f8a6a5311243.png)

For some reason I never gave them labels, but in sysinfo-gui it is hard to figure out which is which.

If drive letters (C:, D:, E:) would show here - it would be easier to identify the disks.

Also I would like to say wow, what a cool program you have made!

**Comment by MoAlyousef** [comment]
Thank you for your words. So it seems it’s the sysinfo::Disk::mount_point. I’ll push a change in a few hours. And hopefully create a new release tomorrow evening.

**Comment by MoAlyousef** [comment]
I have added mount points in release 0.1.10 which show the drive letter on windows. I’m using a smaller font since mount points can be a bit long on macOS.
