### ISSUE TITLE
Add a icon

### ISSUE THREAD

**Issue by martinlindhe** [MoAlyousef/sysinfo-gui#11]
Embedding icon on windows seems a bit involved, but the crate winres seems to simplify it: https://crates.io/crates/winres

For macOS icons, one need to build an app bundle, for example using: https://crates.io/crates/cargo-bundle

I am not sure about how to add icons to a Linux package.

**Comment by MoAlyousef** [comment]
Thank you for the suggestion. I’ll try to find an appropriate icon for the application. For linux, it varies depending on how the app js deployed. I think an appimage is probably easiest and setting an icon for it should be straightforward.
